title: Maurice Bokanga
description: Maurice is a sociological social psychologist whose research focuses on the relational and economic basis of trust and cooperation. His research uses social network analysis, experiments, formal models, and computational methods
theme: jekyll-theme-minimal
